### ISSUE TITLE
Work with other dockers

### ISSUE THREAD

**Issue by haniag** [scotty-c/docker-openvpnas#1]
I know this might not be related to you, but any help would be appreciated. 

I am running a smart DNS proxy (github.com/ab77/netflix-proxy) on my KMV VPS on RamNode. On top of that, I also wanted to add a OpenVPN access server, but your solution isn't working, and I am not sure where the conflict is. 

For my DNS setup, I am disabling IPv6 on VPS in "/etc/network/interfaces" and "/etc/sysctl.conf". Originally your solution didn't build since I got a message about port 443 being in use. When I change that to another port, it builds fine, but I can't access the "host:943/admin" page. 

I thought both solutions being dockers, then they shouldn't interfere, but this is more than my tech prowess.

**Comment by scotty-c** [comment]
Hey @haniag,

Are you using https://DOCKER-IP:943/admin/ ?

You will still need to use HTTPS for the admin site.

**Comment by scotty-c** [comment]
Closing as there has been no reply. Please open again if you have not resolved the issue.
